#!/bin/bash
gps() {
    b=`echo $2 | awk -v s=$1 '{for(i=2; i<=NF; i++) { printf "%d\n", 3600*($i-$(i-1))/s }}' | sort -n | tail -1`
    echo $2 | awk -v s=$1 '{for(i=2; i<=NF; i++) { printf "%d\n", 3600*($i-$(i-1))/s }}' >&2 
    echo $b
}
gps $1 "$2
